<?php
$configFile=__DIR__.'/jukebox-config.json';
$artDir=__DIR__.'/artwork'; if(!is_dir($artDir))@mkdir($artDir,0775,true);
$config=array('title'=>"Ferris & Heidi's Pirate Cove",'subtitle'=>'Choose Your Adventure','enabled'=>true,'allowedPlaylists'=>array(),'artworkSettings'=>array(),'scrollMessage'=>'Welcome aboard! Choose an adventure below.');
if(is_file($configFile)){ $x=json_decode(file_get_contents($configFile),true); if(is_array($x))$config=array_merge($config,$x); }
$dir=isset($settings['playlistDirectory'])?$settings['playlistDirectory']:'/home/fpp/media/playlists';
$available=array(); foreach(glob($dir.'/*.json')?:array() as $f)$available[]=pathinfo($f,PATHINFO_FILENAME);
natcasesort($available); $available=array_values($available);
function fjArtFile($dir,$p){foreach(array('jpg','jpeg','png','webp') as $e){$f=$dir.'/'.$p.'.'.$e;if(is_file($f))return $f;}return '';}
function fjSafeUpload($tmp,$dest,$ext){$info=@getimagesize($tmp);if(!$info)return false;$ok=array(IMAGETYPE_JPEG=>'jpg',IMAGETYPE_PNG=>'png',IMAGETYPE_WEBP=>'webp');if(!isset($ok[$info[2]]))return false;return @move_uploaded_file($tmp,$dest.'.'.$ok[$info[2]]);}
$msg='';$err='';$statsFile=__DIR__.'/jukebox-stats.json';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(isset($_POST['reset_stats'])){file_put_contents($statsFile,json_encode(array('plays'=>array(),'history'=>array()),JSON_PRETTY_PRINT),LOCK_EX);$msg='All Jukebox statistics reset.';}
 elseif(isset($_POST['reset_tonight'])){$sd=array('plays'=>array(),'history'=>array());if(is_file($statsFile)){$sx=json_decode(file_get_contents($statsFile),true);if(is_array($sx))$sd=array_merge($sd,$sx);} $today=date('Y-m-d');$sd['history']=array_values(array_filter($sd['history']??array(),function($h)use($today){return substr((string)($h['time']??''),0,10)!==$today;}));file_put_contents($statsFile,json_encode($sd,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);$msg="Tonight's statistics reset; all-time totals were preserved.";}
 elseif(isset($_POST['art_playlist'])){
  $p=$_POST['art_playlist']; if(!in_array($p,$available,true))$err='Unknown playlist.';
  elseif(isset($_POST['save_position'])){$x=max(0,min(100,(int)($_POST['pos_x']??50)));$y=max(0,min(100,(int)($_POST['pos_y']??50)));$z=max(100,min(200,(int)($_POST['zoom']??100)));$config['artworkSettings'][$p]=array('x'=>$x,'y'=>$y,'zoom'=>$z);file_put_contents($configFile,json_encode($config,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);$msg='Artwork position saved for '.$p;}
  elseif(isset($_POST['delete_art'])){$old=fjArtFile($artDir,$p);if($old&&@unlink($old))$msg='Artwork removed for '.$p;else $err='No artwork to remove.';}
  elseif(!isset($_FILES['artwork'])||$_FILES['artwork']['error']!==UPLOAD_ERR_OK)$err='Choose a JPEG, PNG, or WebP image first.';
  elseif($_FILES['artwork']['size']>8*1024*1024)$err='Artwork must be 8 MB or smaller.';
  else{foreach(array('jpg','jpeg','png','webp') as $e)@unlink($artDir.'/'.$p.'.'.$e);if(fjSafeUpload($_FILES['artwork']['tmp_name'],$artDir.'/'.$p,''))$msg='Artwork updated for '.$p;else $err='That file is not a supported image.';}
 } else {
  $sel=isset($_POST['playlists'])&&is_array($_POST['playlists'])?$_POST['playlists']:array();
  $config=array('title'=>trim($_POST['title']??'')?:"Ferris & Heidi's Pirate Cove",'subtitle'=>trim($_POST['subtitle']??'')?:'Choose Your Adventure','enabled'=>isset($_POST['enabled']),'allowedPlaylists'=>array_values(array_intersect($available,$sel)),'artworkSettings'=>$config['artworkSettings']??array(),'scrollMessage'=>trim($_POST['scrollMessage']??''));
  file_put_contents($configFile,json_encode($config,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);$msg='Jukebox settings saved.';
 }
}
?>
<style>.fj-art-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.fj-art-card{border:1px solid #666;border-radius:10px;padding:10px;background:#181818}.fj-preview{width:100%;aspect-ratio:1.28/1;object-fit:cover;border-radius:7px;background:#30180d;display:block}.fj-empty{display:grid;place-items:center;color:#aaa;border:1px dashed #777}.fj-art-card h5{margin:8px 0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.fj-art-card input[type=file]{width:100%;font-size:.9rem}.fj-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.fj-controls{margin-top:10px}.fj-control{display:grid;grid-template-columns:62px 1fr 42px;gap:6px;align-items:center;margin:5px 0}.fj-control input{width:100%}.fj-val{text-align:right;font-size:.8rem}</style>
<div class="container-fluid"><h2>Ferris Jukebox</h2><p>Select the FPP playlists guests may launch and upload the artwork used for each one.</p>
<?php if($msg):?><div class="alert alert-success"><?=htmlspecialchars($msg)?></div><?php endif;?><?php if($err):?><div class="alert alert-danger"><?=htmlspecialchars($err)?></div><?php endif;?>
<form method="post"><div class="form-group"><label>Guest page title</label><input class="form-control" name="title" value="<?=htmlspecialchars($config['title'])?>"></div>
<div class="form-group"><label>Subtitle</label><input class="form-control" name="subtitle" value="<?=htmlspecialchars($config['subtitle'])?>"></div><div class="form-group"><label>Scrolling guest message</label><input class="form-control" name="scrollMessage" maxlength="240" value="<?=htmlspecialchars($config['scrollMessage']??'')?>" placeholder="Welcome aboard! Choose an adventure below."><small class="form-text text-muted">Leave blank to hide the scrolling message bar.</small></div>
<div class="form-check my-3"><input class="form-check-input" type="checkbox" name="enabled" id="enabled" <?=$config['enabled']?'checked':''?>><label class="form-check-label" for="enabled">Enable guest requests</label></div>
<h4>Allowed Playlists</h4><?php if(!$available):?><div class="alert alert-warning">No playlists found. Create your MP4 playlists in FPP first.</div><?php endif;?>
<?php foreach($available as $p):?><div class="form-check py-1"><input class="form-check-input" type="checkbox" name="playlists[]" value="<?=htmlspecialchars($p)?>" id="p<?=md5($p)?>" <?=in_array($p,$config['allowedPlaylists'],true)?'checked':''?>><label class="form-check-label" for="p<?=md5($p)?>"><?=htmlspecialchars($p)?></label></div><?php endforeach;?>
<button class="btn btn-success mt-3" type="submit">Save Jukebox Settings</button></form><hr>
<h3>Show Artwork</h3><p>Upload a JPEG, PNG, or WebP (maximum 8 MB). Artwork around 1.28:1 fits the guest show tiles best.</p>
<div class="fj-art-grid"><?php foreach($available as $p):$af=fjArtFile($artDir,$p);$as=$config['artworkSettings'][$p]??array('x'=>50,'y'=>50,'zoom'=>100);?><div class="fj-art-card">
<?php if($af):$mime=pathinfo($af,PATHINFO_EXTENSION)==='png'?'image/png':(pathinfo($af,PATHINFO_EXTENSION)==='webp'?'image/webp':'image/jpeg');?><img class="fj-preview" src="data:<?=$mime?>;base64,<?=base64_encode(file_get_contents($af))?>" alt="Artwork for <?=htmlspecialchars($p)?>"><?php else:?><div class="fj-preview fj-empty">No artwork yet</div><?php endif;?>
<h5><?=htmlspecialchars($p)?></h5><form method="post" enctype="multipart/form-data"><input type="hidden" name="art_playlist" value="<?=htmlspecialchars($p,ENT_QUOTES)?>"><input type="file" name="artwork" accept="image/jpeg,image/png,image/webp">
<div class="fj-actions"><button class="btn btn-primary btn-sm" type="submit">Upload / Replace</button><?php if($af):?><button class="btn btn-outline-danger btn-sm" type="submit" name="delete_art" value="1" onclick="return confirm('Remove artwork for <?=htmlspecialchars(addslashes($p),ENT_QUOTES)?>?')">Remove</button><?php endif;?></div><?php if($af):?><div class="fj-controls"><div class="fj-control"><label>X</label><input class="fj-range" type="range" name="pos_x" min="0" max="100" value="<?=$as['x']?>"><span class="fj-val"><?=$as['x']?>%</span></div><div class="fj-control"><label>Y</label><input class="fj-range" type="range" name="pos_y" min="0" max="100" value="<?=$as['y']?>"><span class="fj-val"><?=$as['y']?>%</span></div><div class="fj-control"><label>Zoom</label><input class="fj-range" type="range" name="zoom" min="100" max="200" value="<?=$as['zoom']?>"><span class="fj-val"><?=$as['zoom']?>%</span></div><div class="fj-actions"><button class="btn btn-success btn-sm" type="submit" name="save_position" value="1">Save Position</button><button class="btn btn-secondary btn-sm fj-reset" type="button">Reset</button></div></div><?php endif;?></form></div><?php endforeach;?></div><hr><h3>Jukebox Statistics</h3><?php $sd=array('plays'=>array(),'history'=>array());if(is_file($statsFile)){$sx=json_decode(file_get_contents($statsFile),true);if(is_array($sx))$sd=array_merge($sd,$sx);} $plays=$sd['plays']??array();arsort($plays);$total=array_sum($plays);$tonight=array();$week=array();$today=date('Y-m-d');$cut=time()-7*86400;foreach($sd['history']??array() as $h){$pn=$h['playlist']??'';$ts=strtotime($h['time']??'');if(!$pn||!$ts)continue;if(substr($h['time'],0,10)===$today)$tonight[$pn]=($tonight[$pn]??0)+1;if($ts>=$cut)$week[$pn]=($week[$pn]??0)+1;}arsort($tonight);arsort($week);?><p><strong>Tonight:</strong> <?=array_sum($tonight)?> &nbsp; • &nbsp; <strong>Last 7 days:</strong> <?=array_sum($week)?> &nbsp; • &nbsp; <strong>All time:</strong> <?=$total?></p><?php if($plays):?><table class="table table-striped"><thead><tr><th>Rank</th><th>Show</th><th>Tonight</th><th>7 Days</th><th>All Time</th><th>Share</th></tr></thead><tbody><?php $rank=1;foreach($plays as $pn=>$count):?><tr><td><?=$rank++?></td><td><?=htmlspecialchars($pn)?></td><td><?=$tonight[$pn]??0?></td><td><?=$week[$pn]??0?></td><td><?=$count?></td><td><?=$total?round(($count/$total)*100,1):0?>%</td></tr><?php endforeach;?></tbody></table><?php else:?><p>No guest selections recorded yet.</p><?php endif;?><div class="fj-actions"><form method="post" onsubmit="return confirm('Reset tonight only? All-time totals will be kept.');"><button class="btn btn-warning" type="submit" name="reset_tonight" value="1">Reset Tonight</button></form><form method="post" onsubmit="return confirm('Reset ALL Jukebox statistics? This cannot be undone.');"><button class="btn btn-danger" type="submit" name="reset_stats" value="1">Reset All Statistics</button></form></div>
<hr>
<a class="btn btn-primary" target="_blank" href="plugin.php?plugin=fpp-ferris-jukebox&page=jukebox.php&nopage=1">Open Guest Jukebox</a></div><script>document.querySelectorAll('.fj-art-card').forEach(card=>{const img=card.querySelector('img.fj-preview'),ranges=[...card.querySelectorAll('.fj-range')];if(!img||ranges.length<3)return;const vals=[...card.querySelectorAll('.fj-val')];const draw=()=>{const x=+ranges[0].value,y=+ranges[1].value,z=+ranges[2].value;img.style.objectPosition=x+'% '+y+'%';img.style.transform='scale('+(z/100)+')';vals[0].textContent=x+'%';vals[1].textContent=y+'%';vals[2].textContent=z+'%'};ranges.forEach(r=>r.addEventListener('input',draw));const reset=card.querySelector('.fj-reset');if(reset)reset.addEventListener('click',()=>{ranges[0].value=50;ranges[1].value=50;ranges[2].value=100;draw()});draw()});</script>