<?php
$c=array('title'=>"Ferris & Heidi's Pirate Cove",'subtitle'=>'Choose Your Adventure','enabled'=>true,'allowedPlaylists'=>array(),'artworkSettings'=>array(),'scrollMessage'=>'Welcome aboard! Choose an adventure below.','queueEnabled'=>true,'queueMax'=>3);
$f=__DIR__.'/jukebox-config.json'; if(is_file($f)){ $x=json_decode(file_get_contents($f),true); if(is_array($x))$c=array_merge($c,$x); }
$shell=''; $sf=__DIR__.'/assets/jukebox-shell.jpg'; if(is_file($sf)){ $shell='data:image/jpeg;base64,'.base64_encode(file_get_contents($sf)); }
$donateQr=''; $dqf=__DIR__.'/assets/little-lambs-venmo.png'; if(is_file($dqf)){ $donateQr='plugin.php?plugin=fpp-ferris-jukebox&page=asset.php&nopage=1&type=asset&file=little-lambs-venmo.png'; }
$topShow='';$statsFile=__DIR__.'/jukebox-stats.json';if(is_file($statsFile)){$sd=json_decode(file_get_contents($statsFile),true);$sp=$sd['plays']??array();if($sp){arsort($sp);$topShow=(string)array_key_first($sp);}}
function fjDuration($p){
 $ctx=stream_context_create(array('http'=>array('timeout'=>3)));
 $raw=@file_get_contents('http://127.0.0.1/api/playlist/'.rawurlencode($p),false,$ctx);
 if(!$raw)return '';
 $d=json_decode($raw,true); if(!is_array($d))return '';
 $sec=null;
 if(isset($d['playlistInfo']['total_duration'])&&is_numeric($d['playlistInfo']['total_duration']))$sec=(float)$d['playlistInfo']['total_duration'];
 if(($sec===null||$sec<=0)&&isset($d['mainPlaylist'])&&is_array($d['mainPlaylist'])){ $sum=0;foreach($d['mainPlaylist'] as $e)if(isset($e['duration'])&&is_numeric($e['duration']))$sum+=(float)$e['duration'];if($sum>0)$sec=$sum; }
 if($sec===null||$sec<=0)return '';
 $sec=(int)round($sec); return floor($sec/60).':'.str_pad((string)($sec%60),2,'0',STR_PAD_LEFT);
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title><?=htmlspecialchars($c['title'])?></title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:system-ui,-apple-system,sans-serif;background:#07111b;color:#fff}
.wrap{position:relative;max-width:760px;margin:auto;padding:14px 10px 40px;text-align:center;border-left:6px solid #5b3518;border-right:6px solid #5b3518;box-shadow:inset 10px 0 16px #0008,inset -10px 0 16px #0008;background:linear-gradient(#06111b4d,#06111b4d),<?= $shell ? "url('".$shell."') center top/100% auto no-repeat," : "" ?>#07111b}.clock{position:absolute;top:10px;left:12px;z-index:8;padding:5px 8px;border:1px solid #d8a653;border-radius:7px;background:#080604b8;color:#ffe0a0;font:700 .82rem system-ui,-apple-system,sans-serif;box-shadow:0 2px 6px #000a}.flag{font-size:34px}.eyebrow{text-transform:uppercase;letter-spacing:.18em;font-size:.72rem;color:#e5bd72}
h1{font-family:Georgia,serif;font-size:clamp(1.7rem,7vw,3rem);line-height:1;margin:.2em 0;color:#ffd27a;text-shadow:0 3px 0 #5e2c13}.sub{display:inline-block;font:700 1rem Georgia,serif;color:#2b170a;background:#d7aa63;padding:5px 16px;margin-bottom:10px;border-radius:4px}
.queuebar{display:none;padding:6px 10px;border:1px solid #8c6b3c;border-radius:9px;background:#0c1117dc;margin:0 auto 8px;color:#ffe0a0;font-size:.82rem}.status{padding:9px 10px;border:1px solid #b98a4c;border-radius:10px;background:#120e0bd9;margin:0 auto 8px;min-height:40px;box-shadow:0 3px 10px #000b}.ticker{overflow:hidden;white-space:nowrap;border:1px solid #b98a4c;border-radius:10px;background:#120e0bd9;margin:0 auto 14px;height:34px;line-height:32px;color:#ffe0a0;box-shadow:0 3px 10px #0009}.ticker span{display:inline-block;padding-left:100%;animation:fjscroll 18s linear infinite}@keyframes fjscroll{from{transform:translateX(0)}to{transform:translateX(-100%)}}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px 6px;padding:0 28px}
.show{position:relative;overflow:hidden;width:88%;justify-self:center;aspect-ratio:1.28/1;border:3px solid #d8a653;border-radius:9px;padding:0;background:radial-gradient(circle,#75401f,#211008);color:#fff;font:700 clamp(.78rem,3.4vw,1.05rem) Georgia,serif;box-shadow:0 0 0 1px #4b260f,0 6px 12px #000d;min-height:0}.show:disabled{opacity:.42}.show img{width:100%;height:100%;display:block;object-fit:cover}.show span{position:absolute;left:0;right:0;bottom:0;padding:7px 3px;background:linear-gradient(transparent,#000 38%);text-shadow:0 2px 2px #000}.show.noart span{top:0;display:grid;place-items:center;background:transparent;padding:8px}.popular{position:absolute;right:5px;top:5px;z-index:4;padding:3px 6px;border:1px solid #ffd27a;border-radius:7px;background:#7a260de8;color:#fff1c8;font:700 .67rem system-ui,-apple-system,sans-serif;box-shadow:0 2px 5px #000c}.duration{position:absolute;left:5px;bottom:5px;z-index:3;padding:3px 6px;border:1px solid #d8a653;border-radius:7px;background:#080604d9;color:#ffe0a0;font:700 .72rem system-ui,-apple-system,sans-serif;line-height:1.1;box-shadow:0 2px 5px #000c}
.donate-wrap{margin:28px 14px 8px;padding:16px 12px;border:1px solid #b98a4c;border-radius:12px;background:#120e0bd9;box-shadow:0 3px 10px #0009}.donate-label{font:700 1rem Georgia,serif;color:#ffe0a0;margin-bottom:10px}.donate-qr{display:block;width:min(72%,300px);height:auto;margin:12px auto;border-radius:10px;border:2px solid #d8a653;background:#fff;box-shadow:0 4px 10px #000b}.donate-btn{display:inline-block;padding:10px 20px;border:2px solid #d8a653;border-radius:9px;background:#d7aa63;color:#2b170a;text-decoration:none;font:700 1rem Georgia,serif;box-shadow:0 4px 8px #000b}.foot{margin-top:26px;color:#a9957b;font-size:.78rem}.closed{padding:22px;border:1px solid #744;border-radius:16px;background:#241515}
</style></head><body><main class="wrap"><div class="clock" id="clock"></div><div class="flag">☠️</div><div class="eyebrow">Welcome aboard</div><h1><?php $jt=$c['title']; if(strcasecmp($jt,"Ferris & Heidi's Pirate Cove")===0):?>Ferris &amp; Heidi's<br>Pirate Cove<?php else:?><?=htmlspecialchars($jt)?><?php endif;?></h1><div class="sub"><?=htmlspecialchars($c['subtitle'])?></div>
<div id="status" class="status">Checking the waters…</div><div id="queuebar" class="queuebar"></div><?php if(trim($c['scrollMessage']??'')!==''):?><div class="ticker"><span>🏴‍☠️ <?=htmlspecialchars($c['scrollMessage'])?> &nbsp;&nbsp;&nbsp; ⚓</span></div><?php endif;?>
<?php if(empty($c['enabled'])):?><div class="closed">The Jukebox is closed for now. Check back soon, matey.</div>
<?php elseif(empty($c['allowedPlaylists'])):?><div class="closed">No adventures have been opened yet.</div>
<?php else:?><div class="grid"><?php foreach($c['allowedPlaylists'] as $p):$art='';foreach(array('jpg','jpeg','png','webp') as $ext){$af=__DIR__.'/artwork/'.$p.'.'.$ext;if(is_file($af)){$art='plugin.php?plugin=fpp-ferris-jukebox&page=asset.php&nopage=1&type=artwork&file='.rawurlencode($p.'.'.$ext);break;}}?><button class="show <?=$art?'':'noart'?>" data-playlist="<?=htmlspecialchars($p,ENT_QUOTES)?>"><?php $dur=fjDuration($p);if($art):$as=$c['artworkSettings'][$p]??array('x'=>50,'y'=>50,'zoom'=>100);?><img loading="lazy" decoding="async" src="<?=htmlspecialchars($art,ENT_QUOTES)?>" alt="<?=htmlspecialchars($p,ENT_QUOTES)?>" style="object-position:<?=$as['x']?>% <?=$as['y']?>%;transform:scale(<?=$as['zoom']/100?>)"><?php else:?><span><?=htmlspecialchars($p)?></span><?php endif;?><?php if($p===$topShow):?><b class="popular">🔥 Most Popular</b><?php endif;?><?php if($dur):?><b class="duration"><?=$dur?></b><?php endif;?></button><?php endforeach;?></div><?php endif;?>
<div class="donate-wrap"><div class="donate-label">Enjoyed the shows? Help us share the joy! Tap the QR code below to support Little Lambs Foundation for Kids.</div><?php if($donateQr):?><a href="https://venmo.com/u/littlelambsofutah" target="_blank" rel="noopener"><img class="donate-qr" src="<?=htmlspecialchars($donateQr,ENT_QUOTES)?>" alt="Little Lambs Foundation for Kids Venmo QR code"></a><?php endif;?></div><div class="foot">One adventure at a time • The regular show resumes automatically</div></main><script>
const clock=document.getElementById('clock');const tickClock=()=>{clock.textContent=new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})};tickClock();setInterval(tickClock,1000);
const box=document.getElementById('status'),qbar=document.getElementById('queuebar'),buttons=[...document.querySelectorAll('.show')];let requesting=false,remaining=null,playing='';
const fmt=n=>{n=Math.max(0,Math.round(n||0));return Math.floor(n/60)+':'+String(n%60).padStart(2,'0')};
const paint=()=>{if(remaining!==null&&playing)box.textContent='🎬 Now Playing: '+playing+' • ⏳ '+fmt(remaining)+' remaining'};
setInterval(()=>{if(remaining!==null&&remaining>0){remaining--;paint()}},1000);
const lock=x=>buttons.forEach(b=>b.disabled=x);
async function refresh(){try{const r=await fetch('/api/plugin/fpp-ferris-jukebox/status',{cache:'no-store'}),s=await r.json();
qbar.style.display=s.queueEnabled&&s.queueCount>0?'block':'none';qbar.textContent=s.queueCount>0?'⚓ Up Next: '+s.queue.map((name,i)=>(i+1)+'. '+name).join('  •  '):'';if(!s.enabled){box.textContent='🏴‍☠️ The Jukebox is closed for now.';lock(true)}else if(s.busy){playing=s.currentPlaylist||'Current Show';remaining=Number.isFinite(Number(s.secondsRemaining))?Number(s.secondsRemaining):null;if(remaining!==null)paint();else box.textContent='🎬 Now Playing: '+playing;lock(!s.queueEnabled||s.queueCount>=s.queueMax)}else if(!requesting){remaining=null;playing='';box.textContent='⚓ Ready — choose a show!';lock(false)}}catch(e){box.textContent='⚠️ Jukebox connection unavailable';lock(true)}}
buttons.forEach(b=>b.onclick=async()=>{if(requesting)return;requesting=true;lock(true);box.textContent='🏴‍☠️ Launching '+b.dataset.playlist+'…';
try{const r=await fetch('/api/plugin/fpp-ferris-jukebox/request/'+encodeURIComponent(b.dataset.playlist),{method:'POST'}),d=await r.json();if(!r.ok)throw new Error(d.message||'Request failed');if(d.queued){box.textContent='⚓ '+b.dataset.playlist+' added — you’re #'+d.position+' in the queue';setTimeout(refresh,1800)}else box.textContent='🎬 Now Playing: '+b.dataset.playlist}
catch(e){box.textContent='⚠️ '+e.message;setTimeout(refresh,1200)}finally{requesting=false}});
refresh();setInterval(refresh,2500);
</script></body></html>